### ISSUE TITLE
Not working in Meteor 1.3 beta 4

### ISSUE THREAD

**Issue by st3phan** [TAPevents/tap-i18n#139]
I've created a repo to reproduce: https://github.com/st3phan/meteor-1.3-beta.4-TAPi18n

The repo has 2 branches:
master => Meteor 1.2.1 (working)
1.3-beta.4 = [Meteor 1.3 beta 4](https://github.com/meteor/meteor/issues/5788) (not working)

Also in 1.3-beta.4 `project-tap.i18n` is needed (can be empty) to get rid of the `Uncaught Error: No such function: _` error.

But I can't seem to get the right value for `i18n_files_route`.

Any pointers?

**Comment by bompi88** [comment]
@st3phan Did you get this to work? My app gets built, but only the keys are rendered. @theosp are you currently working on meteor 1.3 support on this package?

**Comment by theosp** [comment]
Hi,

Unfortunately I don't have the resources to add support for beta Meteor releases.

Please note that during Meteor v1.2 betas tap:i18n didn't work for various reasons that weren't related to tap:i18n itself and got fixed by the time v1.2 got stable. Upon v1.2 release minor modifications needed to support the new release.

If a support for v1.3 beta is critical to your project now, you can contact my [Meteor Consultancy](http://www.meteorspark.com/) for help.

Thanks,
-Daniel

**Comment by bompi88** [comment]
@theosp I understand why ;) Looks like it got fixed in `Meteor 1.3 beta 5`.

**Comment by theosp** [comment]
Thanks for the update,

-Daniel
