### ISSUE TITLE
Upgrading to cfs:http-methods@0.0.31 cause crash 

### ISSUE THREAD

**Issue by louis49** [TAPevents/tap-i18n#160]
Error: HTTP.methods not implemented on client-side

at Object.HTTP.methods (.meteor/local/build/programs/server/packages/cfs_http-methods.js:688:9)
W20160406-15:04:26.035(2)? (STDERR)     at [object Object]._.extend._registerHTTPMethod (.meteor/local/build/programs/server/packages/tap_i18n.js:3099:17)
W20160406-15:04:26.036(2)? (STDERR)     at TAPi18n (.meteor/local/build/programs/server/packages/tap_i18n.js:2880:24)
W20160406-15:04:26.036(2)? (STDERR)     at .meteor/local/build/programs/server/boot.js:249:5

**Comment by cpury** [comment]
+1

**Comment by JeanLebrument** [comment]
Omg, I banged my head all the afternoon thinking it came from my side.

**Comment by cpury** [comment]
If anyone finds a work-around, please post it here. This broke all our tests and we're pretty much blocked :(

**Comment by cpury** [comment]
So, I've done some research and the problem seems to be that the `tap-i18n-compiler` imports `cfs_http-methods/http.methods.client.api.js` as a server file, even though it is obviously not.

The only thing that client file does is to overwrite the `HTTP.methods()` function to print out an error: https://github.com/CollectionFS/Meteor-http-methods/blob/master/http.methods.client.api.js

So, to temporarily fix our Circle CI tests until `tap-i18n` fixes their issue, we forked `cfs:http-methods` and kicked out the client file. Voila, green tests again.

**Comment by cpury** [comment]
Great, the same minute I finished my hacky fix, `cfs:http-methods` bumped their version number and that magically fixed it...

https://github.com/CollectionFS/Meteor-http-methods/commits/master

**Comment by rioadrian** [comment]
Is this issue still open after 5 years?
