### ISSUE TITLE
The spacebar '_' helper does not work anymore with Meteor 1.3.2.4

### ISSUE THREAD

**Issue by Billybobbonnet** [TAPevents/tap-i18n#163]
Hello,

I just updated from Meteor 1.3 to 1.3.2.4 and my client code fails because of the spacebars underscore helper. I get a `No such function: _` that I painfully tracked down to the html code helper function rendering in Blaze.

If I downgrade my Meteor version to 1.3, everything start working again.

Does anyone have experienced the same issue? I have trouble to find how to fix this, any idea?

**Comment by vhuerta** [comment]
+1

**Comment by meladawy** [comment]
i hav the same issue...

**Comment by chongwang87** [comment]
same here 😂

**Comment by terenceng2010** [comment]
+1. it seems that `ecmascript` not compatible with tap-i18n.

**Comment by danlg** [comment]
This is a serious issue to upgrade to Meteor 1.3.2.4. @Billybobbonnet  @vhuerta @chongwang87 any workaround?

**Comment by Billybobbonnet** [comment]
none afaik. That's indeed a serious issue.

**Comment by danlg** [comment]
@Billybobbonnet  which precise version of 1.3? 1.3.1 ?1.3.2 ? Version 1.3 had many bugs itself to I want to rollback to the most recent which fixes this issue. Thanks

**Comment by Billybobbonnet** [comment]
just `METEOR@1.3`. I didn't try with other versions than 1.3.2.4

**Comment by danlg** [comment]
ok tried 1.3.2 which doesn't work and** 1.3.1 which works** ;-)

**Comment by juliomac** [comment]
I think there's more to it. 


It works for me on all browsers running Meteor release [1.3.2.4] on '''localhost:3000'''
It works for me on all browsers running Meteor release [1.3.2.4] directly on my application at [libertas.saasmart.com.br](url)

But the intend use of this application is to be embeded inside an iframe. 

Inside an iframe, it only works for me now on Safari (release[1.3.2.4]) . See embedded on page at [clan.netlify.com](url) . On both Chrome and Firefox, it gives error '''Uncaught Error: No such function: _''' and the frame does not show up.

I had my app working fine on all browsers inside an iframe or not on Meteor release [1.2.1]. I have an older version  that can be seen working well in production at [www.markshotel.com.br](url). However, I develop on Safari browser and made many additions to the app to be released at an upcoming version, including the addition of cfs:standard-packages, cfs:gridfs and cfs:ui packages .

I was starting the work on my migration to 1.3, I noticed my 1.2 version wasn't working anymore inside an iframe on Chrome and Firefox. So the issue was already happening on Meteor 1.2.1 The main difference being the addition of those packages. Decided to continue migration as it could be fixed just with updating the packages. However that was not solved.

In SUMMARY:

|                      | No-iframe (All) | iframe Safari |  iframe Chrome/Firefox served on Heroku/Galaxy | iframe Chrome/Firefox      Meteor localhost |
|----------------------|-----------------|---------------|------------------------------------------------|---------------------------------------------|
| Meteor 1.2.1         |        OK       |       OK      |                       OK                       |                      OK                     |
| Meteor 1.2.1 + cfs+? |        OK       |       OK      |               No such function:_               |                      OK                     |
| Meteor 1.3.2.4       |        OK       |       OK      |               No such function:_               |                      OK                     |

Because of this other variables, I suspect it may not be directly attributed to Meteor upgrade.

Doesse any of you have cfs packages installed as well?

**Comment by rsoladan** [comment]
Hi, Im working in some projects with meteor 1.3.2.4 and i have no issues with TAP, I make this little repo with a simple meteor create app and its working fine.

https://github.com/rsoladan/testTAP

Hope it helps.

**Comment by juliomac** [comment]
Thanks @rsoladan ! That reminded me to update my last comment. I found it also had nothing to do with cos packages either.

**Comment by LionelGuerin** [comment]
Hi, I'm working on projects with meteor 1.3.2.4 and i get a _"No such function: _"_. 
So, i forked the testTAP project of @rsoladan (https://github.com/rsoladan/testTAP). 
It seems as if the i18n translation is in package, then there is the error _"No such function: _"_.

Broken : https://github.com/LionelGuerin/testTAP.git

One "patch" solution, is to move your translation files from the package to your global app folders. 
But if another package uses tap-i18n, it will not work until the translations are out of the package folders.

Fixed : https://github.com/LionelGuerin/testTAP/tree/patch

**Comment by DerMarcus** [comment]
Hi, I can confirm @LionelGuerin solution: move the i18n folder to <root>/lib/i18n

**Comment by Billybobbonnet** [comment]
Same here: everything goes back to normal after moving the folder to `/lib/i18n`. Thank you for the fix @LionelGuerin!

**Comment by martinwh99** [comment]
For me the testapp from @rsoladan is working. But for my app i have an emascript error:

Errors prevented startup:

While processing files with ecmascript (for target web.browser):
client/modules/logon/components/login.jsx:28:116: Unexpected token (28:116)

Your application has errors. Waiting for file change.

here is my testapp   [https://github.com/martinwh99/myTestApp](url)
