### ISSUE TITLE
Package depending on deprecated aldeed:simple-schema

### ISSUE THREAD

**Issue by muksyd** [TAPevents/tap-i18n#203]
Hi, 

Please see below, note from the package author: 

> Verify that aldeed:simple-schema is not listed in your .meteor/.versions file. If it is, you likely depend on some other package that has an explicit dependency on the Meteor aldeed:simple-schema package. This could cause problems or unexpected behavior. Work with that package author to get an updated version that does not explicitly depend on the aldeed:simple-schema package.

From:
https://github.com/aldeed/meteor-collection2

Can we update this package so it doesn't explicitly depend on aldeed:simple-schema?

**Comment by alexgzhou** [comment]
second this

**Comment by abate** [comment]
#205 This is a small improvement on this PR

**Comment by haojia321** [comment]
+1, Any timeline we are going to fix this issue?

**Comment by derwaldgeist** [comment]
Any update on this? Guys, I'm about to drop tap:i18n for all the upgrade headaches it is causing. I'm really wondering if this package is even maintained anymore?! Funny, as it is the officially supported i18n package for Meteor. Don't wanna blame the authors, but if you don't want to work on it anymore, deprecate it.

**Comment by danielparas** [comment]
+1

**Comment by raphaelarias** [comment]
+1

**Comment by alexcherpi** [comment]
+1

**Comment by GM-Alex** [comment]
Common the PRs are already done, an update shouldn't be that hard. If you guys don't want to maintain this anymore just say it. I think you will find a new maintainer or people can start using other solutions. But if you want to continue the work on this, merge the changes and release a new version. This is ridiculous, sorry.

**Comment by theosp** [comment]
Hi Alex,

Want to join as maintainer , I'll need to discuss with Chris , but I think
shouldn't be an issue ?

-Daniel

**Comment by haojia321** [comment]
Hi @theosp ,
Any updates please?

**Comment by steven-tib** [comment]
Hi, I was just updating several packages to finally get rid of the deprecated simple-schema but I'm now blocked because of this dependency issue... 

@theosp do you have any update on this? can someone merge the PR as requested many months (year) ago? 

Otherwise, has anyone found a good alternative to tap:i18n package? @derwaldgeist maybe?

**Comment by derwaldgeist** [comment]
I'm now using `universe:i18n` and am quite happy with it. `tap:i18n` just seems to be abandoned. I had so many issues with it since some Meteor releases (e.g. if you use it in packages) that I finally dropped it. It's weird that `tap:i18n` is still recommended by the Meteor guide. IMHO, a solid package for i18n should be part of the Meteor standard instead of relying on the community.

**Comment by steven-tib** [comment]
Thanks @derwaldgeist I'll have a look at `universe:i18n`. I also agree that meteor should have a standard translation package.
