### ISSUE TITLE
Translate metadata

### ISSUE THREAD

**Issue by olivierpascal** [TAPevents/tap-i18n#21]
I don't know if this should be considered as an issue, but I am unable to use tap-i18n for translating metadata in `<head />` (title, description, etc.).

So how to deal with metadata translation with tap-i18n, and more generally how to translate a meteor app in a 'seo-friendly' way with tap-i18n?

**Comment by aesedepece** [comment]
:+1: to this feature request.
Is someone already working on this or is it "OK to take it and work on it"?

**Comment by theosp** [comment]
That will be a big contribution to tap:i18n +1!

**Comment by hynese** [comment]
+1

I just wasted 90 minutes before realising that `<title>{{_ "hello"}}</title>` wouldn't work because of the above!

**Comment by hitchcott** [comment]
Go up-vote this issue: https://github.com/meteor/blaze/issues/11

Or maybe try out this package: https://github.com/kadirahq/meteor-dochead ?

**Comment by hynese** [comment]
Dochead looks ideal for my use case. Thanks for the link.

**Comment by gregorwilson** [comment]
Dochead is a good solution for `<title>` tags, thanks!

**Comment by qbolec** [comment]
I've almost give up with tap-i18n entirely because of this, and here is why.
I am new to Meteor and I am just starting a new project, so it is natural that I start from an almost empty main.html file generated by `meteor create x`. It was natural to me, to test if the i18n works by changing one of the first texts in this file, which is the default `<title>simple</title>` to `<title>{{_ "title"}}</title>`. And since it did not work, I was trying to figure out what I did wrong with configuration/installation for an hour!
