### ISSUE TITLE
Integrate with moment.js

### ISSUE THREAD

**Issue by theosp** [TAPevents/tap-i18n#31]

**Comment by mquandalle** [comment]
I implemented a solution for the LibreBoard project in https://github.com/libreboard/libreboard/commit/74178f4fc9185a4df3ac8891050a7e0f1e10d078. I've forked momentjs, published all locale files as external “assets” and then I load then using an ajax query every time the `TAPi18n` language change. The code is here https://github.com/mquandalle/moment.

**Comment by almogdesign** [comment]
+1

**Comment by gwendall** [comment]
@mquandalle great, you should push your fork to atmosphere!

**Comment by hitchcott** [comment]
Thanks @mquandalle - great package.

However I am having a problem with some languages that don't match up with moment's language keys.

For example, using the locale `zh` in tap:i18n will not match to any moment locale. The relevant file is `zh-cn.js`. I changed the language in tap:i18n to `zh-cn`, but it seems that tap:i18n only supports the specific letter casing - which doesn't match the moment locale file name correctly. Basically I 'solved' this by renaming the locale file in moment.js. Less than ideal, and missing files were returning the meteor app itself with a 200 response code instead of 404.

I guess there'd need to be some kind of layer that maps requests to the right files. Only question is how to prioritise the fallback dialect within a locale.
