### ISSUE TITLE
Couldn't load language 'es' JSON: parsererror

### ISSUE THREAD

**Issue by almogdesign** [TAPevents/tap-i18n#48]
I'm getting the following error "Couldn't load language 'es' JSON: parsererror" 

first everything works fine both no local host and production however if I'm offline I'm getting the error and the app is not translating. 

I'm using app cache and I believe it has something to do with it. Current version tap:i18n                            1.4.0 

This also might be related https://github.com/TAPevents/tap-i18n/issues/6

**Comment by almogdesign** [comment]
I should note I'm using modules and deploying via the modules command line

**Comment by almogdesign** [comment]
It seems that TAPi18n.setLanguage(getUserLanguage()) can't be set offline. It just fails back to EN and has noting to do with a json parse error. Unless it can't find the files when offline. I doubled checked the files and not seeing any issues with in valid json

**Comment by theosp** [comment]
Hi @almogdesign , unfortunately tap:i18n is not supported offline.

tap:i18n designed to load lang files on-demand, and this is one of its unique feature.

Since, offline support requires pre-loading of all the supported languages files, it is not within tap:i18n scope at the moment.

If you'd like to contribute such a feature, the right way to implement that is to add a new option to `project-tap.i18n`, say: `offline-support: true` and make the build plugin load all the supported language to the bundle - the same way it does for the fallback languae `en` today. PR is welcomed :)

-Daniel

**Comment by almogdesign** [comment]
Thanks, bye the way I would make a silent fail it seems once it can't load the lang. file it stops the entire app

**Comment by almogdesign** [comment]
I'm closing this, going to give the following package a test run it seems they have this built in. - https://github.com/gadicc/meteor-messageformat/
