### ISSUE TITLE
Locals not considered if only defined in a package

### ISSUE THREAD

**Issue by gwendall** [TAPevents/tap-i18n#67]
If a package contains a certain language file (say fr.i18n.json) but the app itself does not, the corresponding translation if not made available to the app. Is it the case by design?

Plug: I bumped into this pb whilst working on https://github.com/gwendall/meteor-autoform-i18n

**Comment by theosp** [comment]
Yes, by design,

The app developer controls the supported languages in his project.

From the readme:
"A language is considered supported if it is in the supported_languages array of the project-tap.i18n json. If supported_languages is null or not defined in project-tap.i18n we consider all the languages we find *.i18n.json files to as supported."

I'll make it clearer that it doesn't include *.i18n.json that are inside packages.

Thanks,
-Daniel
