### ISSUE TITLE
Issue with package and tinytest

### ISSUE THREAD

**Issue by bitomule** [TAPevents/tap-i18n#90]
I'm working on a package that uses tapi18n and I get this error during tinytest:

```
TypeError: Object [object Object] has no method '__'
    at Function.format (packages/local-test:bitomule:relativeformatterjs/lib/relativeformatter.es6.js:9:28)
    at Package (packages/local-test:bitomule:relativeformatterjs/tests/tests.js:87:1)
    at [object Object].func (packages/tinytest/tinytest.js:636:1)
    at packages/tinytest/tinytest.js:406:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

My package-tap file is an empty json and I've en and es translation files.

Chrome says error is in line 97 of tap_i18n-client.coffee:

```
TypeError: null is not an object (evaluating 'Template[template]._ = underscore_helper')
```

I don't have templates for this package.

**Comment by theosp** [comment]
Please share a repo where you reproduce the issue.

**Comment by bitomule** [comment]
Here's the package repo https://github.com/bitomule/relativeformatterjs Still WIP

**Comment by bitomule** [comment]
Any ideas @theosp ? Am I doing something wrong?

**Comment by theosp** [comment]
Hi,

Busy with few other things, it will take me some time to get to check it.

-Daniel

**Comment by bitomule** [comment]
Ok, is there anything I can help with to fix it? Thanks.

**Comment by maxenceC** [comment]
Hello, @bitomule  I have exactly the same error, do you have any update on this issue ?

**Comment by bitomule** [comment]
Nope, I just didn't test translations. Can't find way to fix it.

**Comment by schoepke** [comment]
Sorry to revive this almost zombie thread, but it's 2016 and I just ran into the same issue. 
I am using Meteor 1.2.1 (didn't upgrade yet because of 3rd-party incompatibilities) and using Tinytest for package testing, as my app has a numerical core and quite extensive backend functionality.

Translations work when running the app, but fail when unit-testing a package.
I tried a lot of stuff, moving translation files, adding them explicitely to the package.js but nothing works.
It would be nice if the maintainer could at least comment on the status of this bug, as I think it is a major showstopper for serious usage of this i18n package.

The only workaround I found (an use now) is to stub out the TAPi18n.__ function completely with a stubs.js file I load for my package tests and which I execute before running the tests.
e.g.
var i18nOrigFunction = TAPi18n.__;
TAPi18n.__ = function (key) {
  return key;
};
Whether to restore the function and when depends on the use case...
